stages:
  - build
  - test
  - deploy

build:
  stage: build
  image: rust:latest
  script:
    - cargo build
  artifacts:
    paths:
      - target/

test:
  stage: test
  image: rust:latest
  script:
    - cargo test --verbose
  dependencies:
    - build

backwards-compatibility-test:
  stage: test
  image: rust:1.37.0
  script:
    - cargo test --verbose
    
docs:
  stage: deploy
  image: rust:latest
  script:
    - cargo doc
  dependencies:
    - build
  artifacts:
    paths:
      - target/doc/

honggfuzz:
  stage: test
  when: manual
  image: rust:latest
  variables:
    HFUZZ_RUN_ARGS: "\
    --verbose \
    --run_time=1800 \
    --exit_upon_crash \
    --tmout_sigvtalrm \
    --max_file_size=32"
  script:
    - apt update
    - apt install -y build-essential binutils-dev libunwind-dev libblocksruntime-dev
    - cargo install honggfuzz --version="0.5.45"
    - cd fuzz
    - cargo hfuzz run fuzz
    - test ! -e hfuzz_workspace/fuzz/*.fuzz
  dependencies:
    - build
  artifacts:
    when: on_failure
    paths:
      - fuzz/hfuzz_workspace