stages:
  - build
  - test
  - deploy

build:
  stage: build
  image: rust:latest
  script:
    - cargo build
  artifacts:
    paths:
      - target/

test:
  stage: test
  image: rust:latest
  script:
    - cargo test --verbose
  dependencies:
    - build
    
docs:
  stage: deploy
  image: rust:latest
  script:
    - cargo doc
  dependencies:
    - build
  artifacts:
    paths:
      - target/doc/